<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="26" viewBox="0 0 26 26">
  <metadata><?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c138 79.159824, 2016/09/14-01:09:01        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""/>
   </rdf:RDF>
</x:xmpmeta>
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                           
<?xpacket end="w"?></metadata>
<image id="镜像_1_" data-name="镜像 (1)" y="2" width="26" height="18" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAASCAQAAADvEAYoAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAHdElNRQfhARIPMTLTasUsAAABiElEQVQoz4XTPWiTURTG8V/SFOtn6yDY8oJxEF0i2orYrYsolEAHUdciODg5uCo4VgexoHXTQUQkEBArggZbhBInEUSlZLDmCqGICKZGaaUOSdu3NonnLg/nnj+ce55zE2Ub4oCzDXXdQrTxXqIJNCLvh5TNdvreDEquqg49jbMVB12Il4XusFYptaoy3mgRoctLlXAq+vkvBLeUGurbuvyowxY9MBKHzsnYhZypdcVjamE6yhsy64aJcNVbM1GlDmWdVDHnVwyomnNChLwly+666QoWw3hSlx6ditLSijEoJy0t2BT6/LbfgGG9LutUS5RnDGLaUNMZfLIHlBQM2C1SMJzSq+C+SovBXbLNgvc++KjbC089jP6kVAX3Wg1brm5uOG+fbPRkxdx3+v0nwl7XFFYQkiZlHGuL7DBp2ehaJumRz+7Y0oaqKspGsSVNlDnumVdOm29GtFrY5844YtaYo40N6Wj/xmTDyIzHLnqt5ot5S263g+L/abtBh/Thq5KpunfN2vsLjEFr+4RXCl0AAAAASUVORK5CYII="/>
  <image id="edit" x="8" y="10" width="14" height="14" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAQAAAC1QeVaAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAHdElNRQfhARIPMTLTasUsAAAApUlEQVQY03WNIQ7CQBBF36LqahCIVYQroLgBBgOCNBwADgSeG4DCr0TguMBvAgKBKwkhg2lL6cIfM8mbN98ZkDsSXxClA3lK4J5nMXRyBEbAg76/tM2EIfBkwTqyDWUqNNVeppcy4zMYhnrayWRt3AHwVw51zbbxvLrSsnQbdqMhxtg/PCk7q/gNq3I9c+TbrO2TBgpKI2hopq6CTHNn/EqeMub2BokplR01xso5AAAAAElFTkSuQmCC"/>
</svg>
